apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "EstimateAPI.fullname" . }}
  labels:
    {{ include "EstimateAPI.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  secretName: {{ include "EstimateAPI.fullname" . }}-certificate
  dnsNames:
    - {{ include "EstimateAPI.fullname" . }}.{{ .Release.Namespace }}
  subject:
    organizations:
      - RideSaver
  usages:
    - server auth
  issuerRef:
    name: {{ default "ridesaver-ca" .Values.ca.name }}
    kind: {{ default "ClusterIssuer" .Values.ca.type }}
