{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "EstimateAPI.rbacName" . }}
  labels:
    {{ include "EstimateAPI.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "EstimateAPI.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{ end }}
