{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "RequestAPI.serviceAccountName" . }}
  labels:
    {{ include "RequestAPI.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
{{ end }}
