apiVersion: v1
kind: Service
metadata:
  name: {{ include "RequestAPI.fullname" . }}
  labels:
    {{ include "RequestAPI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ range $index, $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $index }}
      protocol: TCP
      name: {{ default $index $port.name }}
    {{ end }}
  selector:
    {{ include "RequestAPI.selectorLabels" . | nindent 4 }}
