apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-gateway
    namespace: server
    labels:
        type: api-gateway
spec:
    selector:
        matchLabels:
            type: api-gateway
    replicas: 1
    template:
        metadata:
            labels:
                type: api-gateway
        spec:
            containers:
                - name: api-gateway
                  image: ghcr.io/ridesaver/api_gateway:latest
                  ports:
                      - containerPort: 80
                      - containerPort: 443
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: api-gateway
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: api-gateway
    minReplicas: 2 # Maintain at least two for redundancy in case on fails
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
    name: api-gateway
    labels:
        type: api-gateway
spec:
    ports:
        - port: 80
          name: http
        - port: 443
          name: https
    selector:
        type: api-gateway
