apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-cert
  namespace: api
spec:
  secretName: identity-cert-secret
  dnsNames:
    - identity-service
    - identity-service.api
  issuerRef:
    name: ridesaver-ca
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: api
  labels:
    type: service
    service: identity
spec:
  selector:
    matchLabels:
      type: service
      service: identity
  replicas: 1
  template:
    metadata:
      namespace: api
      labels:
        type: service
        service: identity
    spec:
      containers:
        - name: identity-service
          image: ghcr.io/ridesaver/identity_service:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: certificate
              mountPath: /certs
              readOnly: true
      volumes:
        - name: certificate
          secret:
            secretName: identity-cert-secret
            optional: true
      imagePullSecrets:
        - name: ridesaver-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: api
  labels:
    type: service
    service: identity
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    type: service
    service: identity
