apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-service-pvc
  namespace: api
spec:
  storageClassName: ""
  volumeName: identity-service-pv
  volumeMode: FileSystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-service-pv
  namespace: api
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: identity-service
    namespace: api
    labels:
        type: service
        service: identity
spec:
    selector:
        matchLabels:
            type: service
            service: identity
    replicas: 1
    template:
        metadata:
            namespace: api
            labels:
                type: service
                service: identity
        spec:
            containers:
                - name: identity-service
                  image: ghcr.io/ridesaver/identity_service:latest
                  ports:
                      - containerPort: 80
                      - containerPort: 443
                  volumeMounts:
                      - mountPath: /data
                        name: identity-service-pv
                - name: identity-memcache
                  image: memcached:1.6-alpine
                  ports:
                      - containerPort: 11211
            volumes:
                - name: identity-service-pv
                  persistentVolumeClaim:
                      claimName: identity-service-pvc
            imagePullSecrets:
                - name: ridesaver-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
    name: identity-service
    namespace: api
    labels:
        type: service
        service: identity
spec:
    ports:
        - port: 80
          name: http
        - port: 443
          name: https
    selector:
        type: service
        service: identity
---
