apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ridesaver-ingress
    namespace: server
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
ingressClassName: nginx
spec:
    tls:
        - hosts:
              - ride-saver.online
    rules:
        - host: ride-saver.online
          http:
              paths:
                  - path: /api
                    pathType: Prefix
                    backend:
                        service:
                            name: api-gateway
                            port:
                                number: 443
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: ui-server
                            port:
                                number: 80
