apiVersion: apps/v1
kind: Deployment
metadata:
    name: location-api
    namespace: api
    labels:
        type: service
        service: location
spec:
    selector:
        matchLabels:
            type: service
            service: location
    replicas: 1
    template:
        metadata:
            labels:
                type: service
                service: location
        spec:
            containers:
                - name: location-api
                  image: ghcr.io/ridesaver/location_service:latest
                  ports:
                      - containerPort: 80
                      - containerPort: 443
                - name: location-memcache
                  image: memcached:1.6-alpine
                  ports:
                      - containerPort: 11211
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: location-api
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: location-api
    minReplicas: 2 # Maintain at least two for redundancy in case on fails
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
    name: location-api
    labels:
        type: service
        service: location
spec:
    ports:
        - port: 80
          name: http
        - port: 443
          name: https
    selector:
        type: service
        service: location
