kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: servicesapi-mssql-data
    namespace: api
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: servicesapi-mssql-deployment
    namespace: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql
            for: service-api
    template:
        metadata:
            namespace: api
            labels:
                app: mssql
                for: service-api
        spec:
            terminationGracePeriodSeconds: 30
            securityContext:
                fsGroup: 10001
            containers:
                - name: servicesapi-mssql
                  image: mcr.microsoft.com/mssql/server:2019-latest
                  resources:
                  ports:
                      - containerPort: 1433
                  env:
                      - name: MSSQL_PID
                        value: "Developer"
                      - name: ACCEPT_EULA
                        value: "Y"
                      - name: MSSQL_SA_PASSWORD
                        value: ST@RTUP_P4SSW0RD
                  volumeMounts:
                      - name: servicesapi-mssqldb
                        mountPath: /var/opt/mssql
            volumes:
                - name: servicesapi-mssqldb
                  persistentVolumeClaim:
                      claimName: servicesapi-mssql-data
---
apiVersion: v1
kind: Service
metadata:
    name: servicesapi-mssql-deployment
    namespace: api
spec:
    selector:
        app: mssql
        for: services-api
    ports:
        - protocol: TCP
          port: 1433
          targetPort: 1433
